/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package spec.swagger.api;

import spec.swagger.model.ErrorResponseDto;
import spec.swagger.model.MyLinkDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "links", description = "the links API")
public interface LinksApi {

    default LinksApiDelegate getDelegate() {
        return new LinksApiDelegate() {};
    }

    @ApiOperation(value = "저장된 모든 링크 가져오기", nickname = "linksGet", notes = "모든 링크 리스트로 가져오기", response = MyLinkDto.class, tags={ "Links", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "성공", response = MyLinkDto.class),
        @ApiResponse(code = 400, message = "실패", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/links",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<MyLinkDto> linksGet() {
        return getDelegate().linksGet();
    }

}
