/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package spec.swagger.api;

import spec.swagger.model.ErrorResponseDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "swaggerTest", description = "the swaggerTest API")
public interface SwaggerTestApi {

    default SwaggerTestApiDelegate getDelegate() {
        return new SwaggerTestApiDelegate() {};
    }

    @ApiOperation(value = "simple swagger test api", nickname = "swaggerTestGet", notes = "simple swagger test api", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = String.class),
        @ApiResponse(code = 400, message = "fail", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/swaggerTest",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<String> swaggerTestGet() {
        return getDelegate().swaggerTestGet();
    }

}
