package me.kdshim.kdd_j.impl;

import me.kdshim.kdd_j.swagger.api.LinksApiDelegate;
import me.kdshim.kdd_j.swagger.model.PostLinkDto;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import javax.xml.ws.Response;
import java.util.List;

@Service
public class LinkApiControllerImpl implements LinksApiDelegate {

    @Override
    public ResponseEntity<PostLinkDto> linksGet() {
        System.out.println("==============================================");
        System.out.println("this is generated by swagger generation code");
        System.out.println("==============================================");
        return ResponseEntity.ok(null);
    }

    @Override
    public ResponseEntity<Void> linksPost(List<PostLinkDto> body) {
        return null;
    }
}
