/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package me.kdshim.kdd_j.swagger.api;

import me.kdshim.kdd_j.swagger.model.ErrorResponseDto;
import me.kdshim.kdd_j.swagger.model.GetSimpleCommitsDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "github", description = "the github API")
public interface GithubApi {

    GithubApiDelegate getDelegate();

    @ApiOperation(value = "kyu9's 도서관 커밋 조회", nickname = "getKyuLibraryCommits", notes = "kyu9's 도서관 커밋 조회", response = GetSimpleCommitsDto.class, tags={ "Github", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "SUCCESS", response = GetSimpleCommitsDto.class),
        @ApiResponse(code = 400, message = "FAIL", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/github/kyu9/library/commits",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<GetSimpleCommitsDto> getKyuLibraryCommits() {
        return getDelegate().getKyuLibraryCommits();
    }

}

