/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package me.kdshim.kdd_j.swagger.api;

import me.kdshim.kdd_j.swagger.model.ErrorResponseDto;
import me.kdshim.kdd_j.swagger.model.GetLinkDto;
import me.kdshim.kdd_j.swagger.model.PostLinkDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "link", description = "the link API")
public interface LinkApi {

    LinkApiDelegate getDelegate();

    @ApiOperation(value = "입력받은 URL을 가진 링크 조회", nickname = "findLinksLikeUrl", notes = "입력값을 LIKE 키워드를 사용해 조회", response = GetLinkDto.class, responseContainer = "List", tags={ "링크", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "SUCCESS", response = GetLinkDto.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "FAIL", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/link/find/{keyword}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<GetLinkDto>> findLinksLikeUrl(@ApiParam(value = "링크에 있는 단어를 기준으로 검색", required=true) @PathVariable("keyword") String keyword) {
        return getDelegate().findLinksLikeUrl(keyword);
    }


    @ApiOperation(value = "URL으로 link 조회", nickname = "findSingleLink", notes = "URL으로 저장한 link를 조회", response = GetLinkDto.class, tags={ "링크", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "SUCCESS", response = GetLinkDto.class),
        @ApiResponse(code = 400, message = "FAIL", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/link/{url}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<GetLinkDto> findSingleLink(@ApiParam(value = "저장해둔 링크를 URL으로 조회", required=true) @PathVariable("url") String url) {
        return getDelegate().findSingleLink(url);
    }


    @ApiOperation(value = "단일 링크 저장", nickname = "saveSingleLink", notes = "단일 링크 저장", response = GetLinkDto.class, tags={ "링크", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "SUCCESS", response = GetLinkDto.class),
        @ApiResponse(code = 400, message = "FAIL", response = ErrorResponseDto.class) })
    @RequestMapping(value = "/link",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<GetLinkDto> saveSingleLink(@ApiParam(value = "" ) @Valid @RequestBody PostLinkDto body) {
        return getDelegate().saveSingleLink(body);
    }

}

